artifacts_root: artifacts

DataIngestion:
  root_dir: artifacts/data_ingestion/
  source_url: ketangangal/heart-disease-dataset-uci
  zipped_file_dir: artifacts/data_ingestion/zip_data/
  unzipped_file_path: artifacts/data_ingestion/heart.csv

DataValidation:
  root_dir: artifacts/data_validation
  unzipped_data_dir: artifacts/data_ingestion/heart.csv
  status_file_path: artifacts/data_validation/status.txt
  
DataTransformation:
  root_dir: artifacts/data_transformation
  unzipped_data_dir: artifacts/data_ingestion/heart.csv
  train_file_path: artifacts/data_transformation
  test_file_path: artifacts/data_transformation
  preprocessor_path: artifacts/data_transformation/preprocessor.joblib
  status_file_path: artifacts/data_validation/status.txt

ModelTrainer: 
  root_dir: artifacts/model_trainer
  processed_data_dir: artifacts/data_transformation
  model_path: artifacts/model_trainer/model.joblib
  